# Generated by Django 4.0.4 on 2022-05-17 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0002_cloudprovider_cloud_access_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudprovider',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='cloudprovider',
            name='cloud_cred_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudprovider',
            name='cloud_cred_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('retries', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed'), (4, 'Retrying')], default=1)),
                ('request_args', models.TextField()),
                ('result_ok', models.TextField(blank=True, null=True)),
                ('result_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
